export type MarketTabId = "futures" | "spot";

export type MarketSeed = {
  slug: string;
  name: string;
  symbol: string;
  pair: string;
  geckoId: string;
  tab: MarketTabId;
  volume: number;
  change24h: number;
  image?: string;
  description?: string;
};

export const marketTabs: Array<{ id: MarketTabId; label: string }> = [
  { id: "futures", label: "Futures" },
  { id: "spot", label: "Spot" },
];

export const futuresMarkets: MarketSeed[] = [
  {
    slug: "btc",
    name: "Bitcoin",
    symbol: "BTC-PERP",
    pair: "BTC-PERP",
    geckoId: "bitcoin",
    tab: "futures",
    volume: 482_000_000,
    change24h: 2.41,
    image: "https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png",
    description: "Bitcoin is a decentralized digital currency, without a central bank or single administrator, that can be sent from user to user on the peer-to-peer bitcoin network without the need for intermediaries.",
  },
  {
    slug: "eth",
    name: "Ethereum",
    symbol: "ETH-PERP",
    pair: "ETH-PERP",
    geckoId: "ethereum",
    tab: "futures",
    volume: 251_000_000,
    change24h: -1.18,
    image: "https://coin-images.coingecko.com/coins/images/279/large/ethereum.png",
    description: "Ethereum is a decentralized, open-source blockchain with smart contract functionality. Ether is the native cryptocurrency of the platform. Among cryptocurrencies, Ether is second only to Bitcoin in market capitalization.",
  },
  {
    slug: "sol",
    name: "Solana",
    symbol: "SOL-PERP",
    pair: "SOL-PERP",
    geckoId: "solana",
    tab: "futures",
    volume: 138_500_000,
    change24h: 4.92,
    image: "https://coin-images.coingecko.com/coins/images/4128/large/solana.png",
    description: "Solana is a high-performance blockchain supporting builders around the world creating crypto apps that scale today. It uses a unique proof-of-history consensus mechanism to achieve high throughput.",
  },
  {
    slug: "xrp",
    name: "XRP",
    symbol: "XRP-PERP",
    pair: "XRP-PERP",
    geckoId: "ripple",
    tab: "futures",
    volume: 114_200_000,
    change24h: -0.66,
    image: "https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png",
    description: "XRP is a digital asset built for payments. It is the native digital asset on the XRP Ledger—an open-source, permissionless and decentralized blockchain technology.",
  },
  {
    slug: "doge",
    name: "Dogecoin",
    symbol: "DOGE-PERP",
    pair: "DOGE-PERP",
    geckoId: "dogecoin",
    tab: "futures",
    volume: 92_000_000,
    change24h: 1.84,
  },
  {
    slug: "ada",
    name: "Cardano",
    symbol: "ADA-PERP",
    pair: "ADA-PERP",
    geckoId: "cardano",
    tab: "futures",
    volume: 88_600_000,
    change24h: 0.93,
  },
  {
    slug: "avax",
    name: "Avalanche",
    symbol: "AVAX-PERP",
    pair: "AVAX-PERP",
    geckoId: "avalanche-2",
    tab: "futures",
    volume: 72_400_000,
    change24h: -2.14,
    image: "https://coin-images.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png",
    description: "Avalanche is an open-source platform for launching decentralized applications and enterprise blockchain deployments in one interoperable, highly scalable ecosystem.",
  },
  {
    slug: "ton",
    name: "Toncoin",
    symbol: "TON-PERP",
    pair: "TON-PERP",
    geckoId: "toncoin",
    tab: "futures",
    volume: 65_100_000,
    change24h: 3.08,
    image: "https://coin-images.coingecko.com/coins/images/17980/large/ton_symbol.png",
    description: "The Open Network (TON) is a fully decentralized layer-1 blockchain designed by Telegram to onboard billions of users. It boasts ultra-fast transactions and low fees.",
  },
  {
    slug: "bnb",
    name: "BNB",
    symbol: "BNB-PERP",
    pair: "BNB-PERP",
    geckoId: "binancecoin",
    tab: "futures",
    volume: 61_000_000,
    change24h: 1.12,
  },
  {
    slug: "sui",
    name: "Sui",
    symbol: "SUI-PERP",
    pair: "SUI-PERP",
    geckoId: "sui",
    tab: "futures",
    volume: 54_300_000,
    change24h: 3.45,
  },
  {
    slug: "matic",
    name: "Polygon",
    symbol: "MATIC-PERP",
    pair: "MATIC-PERP",
    geckoId: "polygon-ecosystem-token",
    tab: "futures",
    volume: 48_700_000,
    change24h: -1.55,
  },
  {
    slug: "ltc",
    name: "Litecoin",
    symbol: "LTC-PERP",
    pair: "LTC-PERP",
    geckoId: "litecoin",
    tab: "futures",
    volume: 43_200_000,
    change24h: 0.78,
  },
  {
    slug: "dot",
    name: "Polkadot",
    symbol: "DOT-PERP",
    pair: "DOT-PERP",
    geckoId: "polkadot",
    tab: "futures",
    volume: 39_800_000,
    change24h: -0.92,
  },
  {
    slug: "apt",
    name: "Aptos",
    symbol: "APT-PERP",
    pair: "APT-PERP",
    geckoId: "aptos",
    tab: "futures",
    volume: 35_600_000,
    change24h: 2.67,
  },
  {
    slug: "op",
    name: "Optimism",
    symbol: "OP-PERP",
    pair: "OP-PERP",
    geckoId: "optimism",
    tab: "futures",
    volume: 31_200_000,
    change24h: -1.34,
  },
  {
    slug: "shib",
    name: "Shiba Inu",
    symbol: "SHIB-PERP",
    pair: "SHIB-PERP",
    geckoId: "shiba-inu",
    tab: "futures",
    volume: 28_900_000,
    change24h: 1.95,
  },
];

export const spotMarkets: MarketSeed[] = [
  {
    slug: "btc",
    name: "Bitcoin",
    symbol: "BTC/USD",
    pair: "BTC/USD",
    geckoId: "bitcoin",
    tab: "spot",
    volume: 1_248_000_000,
    change24h: 2.41,
  },
  {
    slug: "eth",
    name: "Ethereum",
    symbol: "ETH/USD",
    pair: "ETH/USD",
    geckoId: "ethereum",
    tab: "spot",
    volume: 812_000_000,
    change24h: -1.18,
  },
  {
    slug: "sol",
    name: "Solana",
    symbol: "SOL/USD",
    pair: "SOL/USD",
    geckoId: "solana",
    tab: "spot",
    volume: 308_000_000,
    change24h: 4.92,
  },
  {
    slug: "link",
    name: "Chainlink",
    symbol: "LINK/USD",
    pair: "LINK/USD",
    geckoId: "chainlink",
    tab: "spot",
    volume: 188_000_000,
    change24h: 0.74,
  },
  {
    slug: "xrp",
    name: "XRP",
    symbol: "XRP/USD",
    pair: "XRP/USD",
    geckoId: "ripple",
    tab: "spot",
    volume: 174_500_000,
    change24h: -0.66,
  },
  {
    slug: "xlm",
    name: "Stellar Lumens",
    symbol: "XLM/USD",
    pair: "XLM/USD",
    geckoId: "stellar",
    tab: "spot",
    volume: 108_000_000,
    change24h: 1.27,
  },
  {
    slug: "trx",
    name: "TRON",
    symbol: "TRX/USD",
    pair: "TRX/USD",
    geckoId: "tron",
    tab: "spot",
    volume: 99_500_000,
    change24h: 0.48,
  },
  {
    slug: "avax",
    name: "Avalanche",
    symbol: "AVAX/USD",
    pair: "AVAX/USD",
    geckoId: "avalanche-2",
    tab: "spot",
    volume: 87_000_000,
    change24h: -2.14,
  },
  {
    slug: "bnb",
    name: "BNB",
    symbol: "BNB/USD",
    pair: "BNB/USD",
    geckoId: "binancecoin",
    tab: "spot",
    volume: 79_300_000,
    change24h: 1.12,
  },
  {
    slug: "doge",
    name: "Dogecoin",
    symbol: "DOGE/USD",
    pair: "DOGE/USD",
    geckoId: "dogecoin",
    tab: "spot",
    volume: 71_000_000,
    change24h: 1.84,
  },
  {
    slug: "ada",
    name: "Cardano",
    symbol: "ADA/USD",
    pair: "ADA/USD",
    geckoId: "cardano",
    tab: "spot",
    volume: 65_400_000,
    change24h: 0.93,
  },
  {
    slug: "sui",
    name: "Sui",
    symbol: "SUI/USD",
    pair: "SUI/USD",
    geckoId: "sui",
    tab: "spot",
    volume: 58_200_000,
    change24h: 3.45,
  },
  {
    slug: "dot",
    name: "Polkadot",
    symbol: "DOT/USD",
    pair: "DOT/USD",
    geckoId: "polkadot",
    tab: "spot",
    volume: 52_100_000,
    change24h: -0.92,
  },
  {
    slug: "uni",
    name: "Uniswap",
    symbol: "UNI/USD",
    pair: "UNI/USD",
    geckoId: "uniswap",
    tab: "spot",
    volume: 44_700_000,
    change24h: 2.13,
  },
  {
    slug: "matic",
    name: "Polygon",
    symbol: "MATIC/USD",
    pair: "MATIC/USD",
    geckoId: "polygon-ecosystem-token",
    tab: "spot",
    volume: 38_900_000,
    change24h: -1.55,
  },
  {
    slug: "pepe",
    name: "Pepe",
    symbol: "PEPE/USD",
    pair: "PEPE/USD",
    geckoId: "pepe",
    tab: "spot",
    volume: 33_600_000,
    change24h: 4.81,
  },
];

export const allMarkets = [...futuresMarkets, ...spotMarkets];

export const marketBySlug = new Map(
  allMarkets.map((market) => [market.slug, market] as const),
);

export function getMarketBySlug(slug: string) {
  return marketBySlug.get(slug.toLowerCase());
}

export function getMarketsForTab(tab: MarketTabId) {
  return tab === "futures" ? futuresMarkets : spotMarkets;
}

export function getUniqueGeckoIds(markets: MarketSeed[]) {
  return [...new Set(markets.map((market) => market.geckoId))];
}
